# Generated by Django 4.0.5 on 2022-08-10 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=500, verbose_name='نام کتاب')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='قیمت')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('description', models.TextField(max_length=1000, verbose_name='توضیحات')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('p', 'publish'), ('n', 'draft')], max_length=1)),
                ('photo', models.ImageField(upload_to='images/', verbose_name='عکس')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='عکس')),
                ('description', models.TextField(max_length=1000, verbose_name='توضیحات')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=700)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_key', to='admin_post.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(related_name='categorys', to='admin_post.category'),
        ),
        migrations.AddField(
            model_name='books',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='shop_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
